# UnitsDataArray

UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)

In [31]:
import numpy as np
from podpac import Node, Coordinates

In [32]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.278393, 0.519213, 0.970743, 0.264014, 0.97926 ],
       [0.283064, 0.974952, 0.602771, 0.612484, 0.12286 ],
       [0.654267, 0.724464, 0.081258, 0.694314, 0.986847],
       [0.076126, 0.916126, 0.627588, 0.904229, 0.96175 ],
       [0.963371, 0.729748, 0.177577, 0.867323, 0.594614]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x1c1f846400>
    units:        None

In [33]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.27839318, 0.51921347, 0.97074301, 0.26401368, 0.97925967],
       [0.28306398, 0.97495236, 0.60277125, 0.61248364, 0.12286022],
       [0.65426732, 0.72446427, 0.0812584 , 0.69431421, 0.98684653],
       [0.07612637, 0.91612571, 0.6275878 , 0.90422863, 0.96175046],
       [0.96337142, 0.72974753, 0.17757671, 0.86732291, 0.59461437]])

In [34]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.278393, 0.519213, 0.970743, 0.264014, 0.97926 ])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x1c1f846400>
    units:        None

In [42]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [43]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [44]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [46]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [25]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.31491 , 0.94718 , 0.031065, 0.229489, 0.475143])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x10cab4390>
    units:        None

In [26]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [27]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)