# UnitsDataArray

UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)

In [11]:
import numpy as np
from podpac import Node

In [45]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.054578, 0.942669, 0.545054, 0.189823, 0.716969],
       [0.338922, 0.300583, 0.12003 , 0.964723, 0.764554],
       [0.546585, 0.910471, 0.690243, 0.761469, 0.907821],
       [0.160873, 0.085718, 0.91427 , 0.901375, 0.764637],
       [0.571522, 0.353221, 0.68945 , 0.075019, 0.448275]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x1c2374f208>
    units:        None

In [40]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.94530436, 0.12521433, 0.67357558, 0.6241213 , 0.25374485],
       [0.24989489, 0.6035315 , 0.60863362, 0.6416228 , 0.3920896 ],
       [0.83446444, 0.09304617, 0.52418154, 0.73482263, 0.17170687],
       [0.75717915, 0.74316486, 0.57358115, 0.04720775, 0.96356234],
       [0.02944918, 0.63291924, 0.53221914, 0.58217447, 0.71497121]])

In [42]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [43]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [44]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [46]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [50]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.452872, 0.262097, 0.186283, 0.708614, 0.216625])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x1c23782c50>
    units:        None

In [52]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [51]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)