# UnitsDataArray

UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)

In [1]:
import numpy as np
from podpac import Node, Coordinates

In [2]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.53787 , 0.81529 , 0.390143, 0.603575, 0.584164],
       [0.586335, 0.260835, 0.519169, 0.434898, 0.784125],
       [0.758956, 0.961084, 0.402557, 0.38513 , 0.318223],
       [0.957541, 0.407683, 0.802978, 0.469193, 0.096684],
       [0.114779, 0.964258, 0.493893, 0.762606, 0.256869]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000199AAF19C88>
    units:        None

In [3]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.53786977, 0.81528998, 0.39014277, 0.60357549, 0.58416434],
       [0.58633472, 0.26083465, 0.51916889, 0.43489765, 0.78412549],
       [0.75895623, 0.96108399, 0.40255681, 0.38513008, 0.31822291],
       [0.95754052, 0.40768338, 0.80297768, 0.46919321, 0.09668368],
       [0.11477894, 0.96425813, 0.4938934 , 0.76260572, 0.25686891]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.53787 , 0.81529 , 0.390143, 0.603575, 0.584164])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000199AAF19C88>
    units:        None

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.239107, 0.345053, 0.132429, 0.639659, 0.315308])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000199AAF19EF0>
    units:        None

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)