In [1]:
from podpac import DataSource
from podpac.core.units import UnitsDataArray

import numpy as np
from podpac.core.data.test.test_datasource import MockDataSource, MockEmptyDataSource, MockNonuniformDataSource, DATA, COORDINATES
from podpac.core.coordinates import Coordinates, clinspace

In [2]:
c = Coordinates()

In [3]:
node = MockDataSource()

In [4]:
node.native_coordinates = 'not'

In [5]:
node = DataSource(source= np.random.rand(101, 101), native_coordinates=None)

In [6]:
node.native_coordinates

In [7]:
node._interpolation

TraitError: DataSource _interpolation property set during evaluate

In [11]:
node.base_definition

OrderedDict([('node', 'core.data.test.test_datasource.MockDataSource'),
             ('source',
              array([[10.        ,  1.        ,  0.43732015, ...,  0.60035881,
                       0.6909822 ,  0.5405175 ],
                     [ 5.        ,         nan,  0.03074387, ...,  0.5110757 ,
                       0.2727393 ,  0.57509833],
                     [ 0.80899026,  0.75298301,  0.76801868, ...,  0.94997287,
                       0.66378391,  0.67558844],
                     ...,
                     [ 0.78666983,  0.15361324,  0.27790125, ...,  0.23902221,
                       0.99165978,  0.78029164],
                     [ 0.84869849,  0.58749081,  0.99831618, ...,  0.55423208,
                       0.19628102,  0.45826496],
                     [ 0.42764083,  0.6547428 ,  0.42627069, ...,  0.81564064,
                       0.20026049,  0.17013063]])),
             ('interpolator', '')])

In [2]:
node= MockDataSource()
coords_subset = node.native_coordinates.intersect(node.native_coordinates)
coords_subset_slc = node.native_coordinates.intersect(node.native_coordinates, return_indices=True)
coords_subset_slc

(Coordinates
 	lat: UniformCoordinates1d(lat): Bounds[-25.0, 25.0], N[101], ctype['midpoint']
 	lon: UniformCoordinates1d(lon): Bounds[-25.0, 25.0], N[101], ctype['midpoint'],
 [slice(None, None, None), slice(None, None, None)])

In [6]:
a = tuple()

In [9]:
{a:'test'}.keys()

dict_keys([()])

In [3]:
node.execute(node.native_coordinates)

set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interpolation
set interp

RecursionError: maximum recursion depth exceeded in comparison

In [10]:
node.output

<xarray.UnitsDataArray (lat: 101, lon: 101)>
array([[10.      ,  1.      ,  0.356518, ...,  0.410831,  0.472142,  0.920704],
       [ 5.      ,       nan,  0.44245 , ...,  0.983112,  0.160459,  0.827442],
       [ 0.913907,  0.832108,  0.484692, ...,  0.388316,  0.834022,  0.629425],
       ...,
       [ 0.576343,  0.96804 ,  0.452214, ...,  0.682183,  0.978523,  0.267091],
       [ 0.867356,  0.6522  ,  0.50615 , ...,  0.870238,  0.468136,  0.105479],
       [ 0.925004,  0.84789 ,  0.989152, ...,  0.973966,  0.063055,  0.64484 ]])
Coordinates:
  * lat      (lat) float64 -25.0 -24.5 -24.0 -23.5 -23.0 -22.5 -22.0 -21.5 ...
  * lon      (lon) float64 -25.0 -24.5 -24.0 -23.5 -23.0 -22.5 -22.0 -21.5 ...
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c18243668>

In [7]:
node = MockDataSource()
coords = Coordinates(lat=(-25, 0, 13), lon=(-25, 0, 13), order=['lat', 'lon'])
data, coords_subset = node.get_data_subset(coords)
print(data.shape)
print(data.lat)
print(np.min(data.lat.values))

(52, 52)
<xarray.UnitsDataArray 'lat' (lat: 52)>
array([-25. , -24.5, -24. , -23.5, -23. , -22.5, -22. , -21.5, -21. , -20.5,
       -20. , -19.5, -19. , -18.5, -18. , -17.5, -17. , -16.5, -16. , -15.5,
       -15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5, -11. , -10.5,
       -10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,  -5.5,
        -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,
         0. ,   0.5])
Coordinates:
  * lat      (lat) float64 -25.0 -24.5 -24.0 -23.5 -23.0 -22.5 -22.0 -21.5 ...
-25.0


In [130]:
node = MockDataSource(interpolation='nearest_preview')
coords = Coordinate(lat=(-25, 0, 20), lon=(-25, 0, 20), order=['lat', 'lon'])
data, coords_subset = node.get_data_subset(coords)
coords_subset.shape
data.shape

(18, 18)

In [131]:
node = MockDataSource(interpolation='nearest_preview')
coords = Coordinate(lat=(-25, 0, 20), lon=(-25, 0, 20), time=(1, 10, 10), order=['lat', 'lon', 'time'])
data, coords_subset = node.get_data_subset(coords)
coords_subset.shape
coords_subset

Coordinate
	lat: UniformCoord: Bounds[-25.0, 0.5], N[18], ctype["segment"]
	lon: UniformCoord: Bounds[-25.0, 0.5], N[18], ctype["segment"]

In [133]:
node = MockDataSource(interpolation='nearest_preview')
coords = Coordinate(lat=(-25, 0, 20), order=['lat'])
data, coords_subset = node.get_data_subset(coords)
coords_subset.shape
data.shape

(18, 101)

In [134]:
node = MockDataSource(interpolation='nearest_preview')
coords = Coordinate(lat=[-25, -10, -5], order=['lat'])
data, coords_subset = node.get_data_subset(coords)
coords_subset.shape
data.shape

(3, 101)

In [8]:
node = MockDataSource()
node.execute()

TypeError: execute() missing 1 required positional argument: 'coordinates'

In [11]:
node = MockDataSource()
output = node.execute(node.native_coordinates)
output

In [33]:
node = MockDataSource()
coords = Coordinate(lat=(-25, 0, 20), lon=(-25, 0, 20), time=(1, 10, 10), order=['lat', 'lon', 'time'])
output = node.execute(coords)
output

<xarray.UnitsDataArray (lat: 20, lon: 20)>
array([[0.402081, 0.180183, 0.788923, ..., 0.312137, 0.191326, 0.548026],
       [0.909854, 0.212722, 0.369243, ..., 0.887062, 0.370301, 0.777282],
       [0.222237, 0.638694, 0.893758, ..., 0.158085, 0.080099, 0.150241],
       ...,
       [0.041678, 0.757213, 0.44812 , ..., 0.160469, 0.289663, 0.832238],
       [0.037744, 0.003196, 0.673412, ..., 0.783172, 0.98501 , 0.974563],
       [0.00606 , 0.088103, 0.570319, ..., 0.287292, 0.961129, 0.184044]])
Coordinates:
  * lat      (lat) float64 -25.0 -23.68 -22.37 -21.05 -19.74 -18.42 -17.11 ...
  * lon      (lon) float64 -25.0 -23.68 -22.37 -21.05 -19.74 -18.42 -17.11 ...
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c17f8b5c0>
    params:       {'interpolation': 'nearest'}

In [35]:
node = MockDataSource()
coords = Coordinate(lat=(-55, -45, 20), lon=(-55, -45, 20), order=['lat', 'lon'])
output = node.execute(coords)
output

<xarray.UnitsDataArray (lat: 20, lon: 20)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * lat      (lat) float64 -55.0 -54.47 -53.95 -53.42 -52.89 -52.37 -51.84 ...
  * lon      (lon) float64 -55.0 -54.47 -53.95 -53.42 -52.89 -52.37 -51.84 ...
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c17f8bcc0>
    params:       {'interpolation': 'nearest'}

In [6]:
node = MockDataSource(no_data_vals=[10, None])
output = node.execute(node.native_coordinates)
output.values[np.isnan(output)].shape

(2,)

In [8]:
node = MockDataSource()
coords = Coordinate(lat=(-55, -45, 20), lon=(-55, -45, 20), order=['lat', 'lon'])
output = node.execute(coords)
np.all(np.isnan(output))

True

In [35]:
node = MockDataSource()
UnitsDataArray(np.zeros(node.source.shape), coords=node.native_coordinates.coords, dims=node.native_coordinates.dims)

<xarray.UnitsDataArray (lat: 101, lon: 101)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Coordinates:
  * lat      (lat) float64 -25.0 -24.5 -24.0 -23.5 -23.0 -22.5 -22.0 -21.5 ...
  * lon      (lon) float64 -25.0 -24.5 -24.0 -23.5 -23.0 -22.5 -22.0 -21.5 ...

In [46]:
node = MockDataSource()
coords = Coordinate(lat=(-55, -45, 101), lon=(-55, -45, 101), order=['lat', 'lon'])
output = UnitsDataArray(np.zeros(node.source.shape),
                        coords=coords.coords,
                        dims=coords.dims)
output = node.execute(coords, output=output)
np.isnan(output[0, 0])

<xarray.DataArray ()>
array(True)
Coordinates:
    lat      float64 -55.0
    lon      float64 -55.0

In [42]:
node = MockDataSource()
output = UnitsDataArray(np.zeros(node.source.shape),
                        coords=node.native_coordinates.coords,
                        dims=node.native_coordinates.dims)
node.execute(node.native_coordinates, output=output)

output[0, 0] == 10

<xarray.UnitsDataArray ()>
array(False)
Coordinates:
    lat      float64 -25.0
    lon      float64 -25.0

In [2]:
source = np.random.rand(1,1)
coords_src = Coordinate(lat=[20], lon=[20], order=['lat', 'lon'])
coords_dst = Coordinate(lat=[20], lon=[20], order=['lat', 'lon'])

node = DataSource(source=source, native_coordinates=coords_src)
data_subset, coords_subset = node.get_data_subset(coords_dst)
node._interpolate_data(data_subset, coords_subset, coords_dst)

<xarray.UnitsDataArray (lat: 1, lon: 1)>
array([[0.833761]])
Coordinates:
  * lat      (lat) float64 20.0
  * lon      (lon) float64 20.0
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c1b3a01d0>
    params:       {}

In [15]:
source = np.random.rand(1,1)
coords_src = Coordinate(lat=[20], lon=[20], order=['lat', 'lon'])
coords_dst = Coordinate(lat=[20], lon=[20], order=['lat', 'lon'])

# TODO: this doesn't work, but I feel like it shold
# coords_dst = Coordinate(lat=[21], lon=[21], order=['lat', 'lon'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
data, coords_subset = node.get_data_subset(coords_dst)
output = node._interpolate_data(data, coords_subset, coords_dst)

In [18]:
np.prod(coords_dst.shape)

1

In [20]:
source = np.random.rand(5)
coords_src = Coordinate(lat=(0, 10, 5), order=['lat'])
coords_dst = Coordinate(lat=[1, 1.2, 1.5, 5, 9], order=['lat'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
node.interpolation = 'nearest_preview'

output = node.execute(coords_dst)

output

<xarray.UnitsDataArray (lat: 5)>
array([0.861676,      nan, 0.377369, 0.003592, 0.238238])
Coordinates:
  * lat      (lat) float64 1.0 1.2 1.5 5.0 9.0
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c1cbb4550>
    params:       {'interpolation': 'nearest_preview'}

In [15]:
source = np.random.rand(5)
coords_src = Coordinate(time=(0, 10, 5), order=['time'])
coords_dst = Coordinate(time=(1, 11, 5), order=['time'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)

output = node.execute(coords_dst)
np.all(output.time.values == coords_dst.coords['time'])

True

In [2]:
source = np.random.rand(5)
coords_src = Coordinate(alt=(0, 10, 5), order=['alt'])
coords_dst = Coordinate(alt=(1, 11, 5), order=['alt'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
output = node.execute(coords_dst)

In [2]:
source = np.random.rand(5,5)
coords_src = Coordinate(lat=(0, 10, 5), lon=(0, 10, 5), order=['lat', 'lon'])
coords_dst = Coordinate(lat=(2, 12, 5), lon=(2, 12, 5), order=['lat', 'lon'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
node.interpolation = 'bilinear'
output = node.execute(coords_dst)
output

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.110103, 0.726358, 0.683293, 0.642199,      nan],
       [0.22125 , 0.233812, 0.577178, 0.465197,      nan],
       [0.335269, 0.70526 , 0.53053 , 0.729101,      nan],
       [0.712626, 0.785848, 0.803722, 0.497323,      nan],
       [     nan,      nan,      nan,      nan,      nan]])
Coordinates:
  * lat      (lat) float64 2.0 4.5 7.0 9.5 12.0
  * lon      (lon) float64 2.0 4.5 7.0 9.5 12.0
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1c20552208>
    params:       {'interpolation': 'bilinear'}

In [5]:
coords_dst['lat'].scipy_regularity

True

In [33]:
source = np.random.rand(5)
coords_src = Coordinate(lat_lon=([0, 2, 4, 6, 8, 10], [0, 2, 4, 5, 6, 10]))
coords_dst = Coordinate(lat_lon=([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]))

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
output = node.execute(coords_dst)

# coords_dst = Coordinate(lat=[1, 2, 3, 4, 5], lon=[1, 2, 3, 4, 5], order=['lat', 'lon'])
# output = node.execute(coords_dst)

In [43]:
source = np.random.rand(5, 5)
coords_src = Coordinate(lat=(0, 10, 5), lon=(0, 10, 5), order=['lat', 'lon'])
coords_dst = Coordinate(lat_lon=([0, 2, 4, 6, 8, 10], [0, 2, 4, 5, 6, 10]))

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
node.interpolation = 'nearest'
output = node.execute(coords_dst)

In [45]:
source

array([[0.71231952, 0.10960281, 0.79947836, 0.88116954, 0.01321961],
       [0.37863486, 0.61287449, 0.16611153, 0.62110283, 0.57714457],
       [0.00269476, 0.16923126, 0.36326341, 0.18666607, 0.54373191],
       [0.20597112, 0.11935562, 0.86889142, 0.08912899, 0.46883606],
       [0.7946778 , 0.62003758, 0.04920923, 0.45902613, 0.0669611 ]])

In [46]:
output.lat_lon.values

array([( 0.,  0.), ( 2.,  2.), ( 4.,  4.), ( 6.,  5.), ( 8.,  6.),
       (10., 10.)], dtype=[('lat', '<f8'), ('lon', '<f8')])

In [2]:
import rasterio

ImportError: dlopen(/Users/marcus/computing/python/anaconda3/envs/podpac/lib/python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgssapi_krb5.2.2.dylib
  Referenced from: /Users/marcus/computing/python/anaconda3/envs/podpac/lib/libdapclient.6.dylib
  Reason: image not found

In [2]:
source = np.random.rand(5)
coords_src = Coordinate(lat=(0, 10, 5), order=['lat'])
coords_dst = Coordinate(lat=[1, 1.2, 1.5, 5, 9], order=['lat'])

node = MockEmptyDataSource(source=source, native_coordinates=coords_src)
node.interpolation = 'nearest_preview'
output = node.execute(coords_dst)

In [7]:
node.output

<xarray.UnitsDataArray (lat: 5)>
array([0.185934, 0.151691, 0.60309 , 0.007854, 0.418466])
Coordinates:
  * lat      (lat) float64 0.0 2.5 5.0 7.5 10.0
Attributes:
    layer_style:  <podpac.core.node.Style object at 0x1108faf28>